In [2]:
from utils_and_constants import (
    DROP_COLNAME, TARGET_COLUMN, RAW_DATASET, 
    PROCESSED_DATASET, CATEGORICAL_COLS, NUMERICAL_COLS
)

In [3]:
DROP_COLNAME

['ID', 'Customer_ID', 'Name', 'SSN', 'Month', 'Type_of_Loan', 'Occupation']

In [25]:
from load_data import load_data

In [26]:
df = load_data(
        file_path=RAW_DATASET, drop_columns=DROP_COLNAME, target_column=TARGET_COLUMN
    )

df.head()

    Age Annual_Income  ...     Monthly_Balance  Credit_Score
0    23      19114.12  ...  312.49408867943663             0
1    23      19114.12  ...  284.62916249607184             0
2  -500      19114.12  ...   331.2098628537912             0
3    23      19114.12  ...  223.45130972736786             0
4    23      19114.12  ...  341.48923103222177             0

[5 rows x 21 columns]

In [27]:
from preprocess_data import preprocess_data

In [28]:
df_processed = preprocess_data(df)

In [29]:
df_processed.head()

    Age  Annual_Income  ...  Monthly_Balance  Credit_Score
0  23.0       19114.12  ...       312.494089             0
1  23.0       19114.12  ...       223.451310             0
2  23.0       19114.12  ...       341.489231             0
3  23.0       19114.12  ...       340.479212             0
4  23.0       19114.12  ...       244.565317             0

[5 rows x 21 columns]

In [34]:

from transformed import transformed_data

transformed_data = transformed_data(df=df_processed, target_column=TARGET_COLUMN, 
                                    categorical_cols=CATEGORICAL_COLS, numerical_cols=NUMERICAL_COLS)

transformed_data.head()

   num__Age  ...  cat__Payment_Behaviour_NPB
0 -0.955977  ...                         0.0
1 -0.955977  ...                         0.0
2 -0.955977  ...                         0.0
3 -0.955977  ...                         1.0
4 -0.955977  ...                         0.0

[5 rows x 29 columns]